### PR TITLE
Bump deps to work with circe 0.13.0

### PR DESCRIPTION
**Pull request by sshkel**
Hi folks,
Not sure what your policy is for bumping dependencies, but wanted to see if I could run this update.
I am trying to use your cool library with sttp and they have lately bumped their circe and jawn deps, which made things incompatible. 
Any chance we can refresh the versions used in this project?
Cheers,
Stanis

### CODE REVIEW

**Comment by sshkel** [comment]
Hmm, it looks like jawn dropped support for scala 2.11. Not sure if that is something will be happy to do. Let me know.

**Comment by Avasil** [comment]
Hi, thanks for PR!

I think it's fine to drop 2.11

**Comment by sshkel** [comment]
Easy! Let me know if there is something else I need to do.

**Comment by Avasil** [comment]
I will try to run the release today's evening but I'm using a different computer temporarily so I'm not sure if sonatype will like my keys

**Comment by sshkel** [comment]
All good, man. No rush, you've been super quick in reviewing my stuff anyway. Enjoy your weekend :)

**Comment by Avasil** [comment]
Yeah, I have a wrong setup here and unfortunately I don't have time to fix it right now. I should have access to my laptop around Wednesday, ping me if there's no release until then :)

**Comment by sshkel** [comment]
Yeah, all good, i am not in a rush. 
That was always plan B :)

**Comment by sshkel** [comment]
@Avasil wanted to remind about this.

**Comment by Avasil** [comment]
Thanks, I will release today :)

**Comment by Avasil** [comment]
`0.0.3` should be available

**Comment by sshkel** [comment]
Epic! thanks heaps

**Pull request merged**
